staticSites:
  - name: movies-frontend
    staticPublishPath: frontend/dist
    buildCommand: cd frontend && npm ci && npm run build
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
